// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");
var RecordTuplePolyfill = require("@bloomberg/record-tuple-polyfill");

function fromArray(array) {
  return RecordTuplePolyfill.Tuple.from(array);
}

function toArray(tuple) {
  return Array.from(tuple);
}

var get = Caml_array.get;

exports.fromArray = fromArray;
exports.toArray = toArray;
exports.get = get;
/* @bloomberg/record-tuple-polyfill Not a pure module */
